language: node_js
node_js:
  - "5.1"

services:
  - redis-server

env:
  - NODE_ENV=travis REDIS_HOST=localhost REDIS_PORT=6379

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm test
